First version of SystemC backend

diff --git a/examples/full/Do_test b/examples/full/Do_test
--- a/examples/full/Do_test
+++ b/examples/full/Do_test
@@ -1,14 +1,22 @@
 #!/bin/bash
 
+RFSMMAKE=/Users/jserot/Dev/ml/rfsm/etc/bin/rfsmmake
+RFSMLIB=/Users/jserot/Dev/ml/rfsm/etc
+RFSMC=/Users/jserot/Dev/ml/rfsm/_build/default/src/bin/full/rfsmc.bc # Current version
+RFSMC_PRE=/Applications/RfsmLight.app/Contents/MacOS/rfsmc # Previous version
+
+
 # A script for automated testing 
 
-function try_make
+try_make ()
 {
 case $1 in
-type) make type;;
 dot) make dot.run;;
 sim) make sim.run;;
 ctask) make ctask;;
+systemc) make systemc;;
+systemc.code) make systemc.code;;
+systemc.run) make systemc.run;;
 *) false;;
 esac
 case $? in
@@ -51,8 +59,8 @@ function make_test
 
 TMP=/tmp/do_test.out
 
-if [ $1 = "all" ]
-then
+make_all ()
+{
     shift
     echo "** Testing all in $1... "
     make_test $1 2>&1
@@ -61,7 +69,10 @@ then
     else
         exit 1
     fi
-else 
+}
+
+make_target ()
+{
     echo -n "Testing $1 in $2... "
     (cd $2; if [ -e Makefile ]; then make clobber > $TMP 2>&1; fi)
     (cd $2; try_make $1 && make clean) > $TMP 2>&1
@@ -69,4 +80,57 @@ else
     grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
     grep "OK" $TMP >/dev/null && exit 1
     exit 0
-fi
+}
+
+make_target_comp () # For regression testing
+{
+    echo -n "Making $1 in $2 (with $RFSMC_PRE)..."
+    (cd $2; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC_PRE -o Makefile ./main.pro > $TMP 2>&1)
+    case $1 in
+        systemc) (cd $2; try_make $1.code) >> $TMP 2>&1;;
+        *) (cd $2; try_make $1) >> $TMP 2>&1
+    esac
+    grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
+    grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
+    (cd $2; if [ -e ./$1 ]; then rm -rf ./$1.pre; cp -r ./$1 ./$1.pre; fi)
+    (cd $2; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC -o Makefile ./main.pro >> $TMP 2>&1)
+    echo -n "Making $1 in $2 (with $RFSMC)..."
+    case $1 in
+        systemc) (cd $2; try_make $1.code) >> $TMP 2>&1;;
+        *) (cd $2; try_make $1) >> $TMP 2>&1
+    esac
+    grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
+    grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
+    echo "Comparing results..."
+#   IFS=$'\n' read -d '' -a files < "$2/rfsm.output"
+#   for f in ${files[@]}; do
+#     for f in $2/$1/*; do
+#         name=`basename $f`
+#         diff -E -b -B --unified=0 -q --exclude=Makefile $2/$1.pre/$name $2/$1/$name
+#     done
+    case $3 in
+#        show) diff -B --unified=0 -r --exclude=Makefile $2/$1.pre $2/$1;;
+        show) diff -d -B -r --exclude=Makefile $2/$1.pre $2/$1;;
+        *) diff -q -d -B --unified=1 -r --exclude=Makefile $2/$1.pre $2/$1;;
+    esac
+#    rm -rf $2/$1.pre
+}
+
+make_makefile ()
+{
+    echo -n "Making Makefile in $1... "
+    (cd $1; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC -o Makefile ./main.pro > $TMP 2>&1)
+    grep "Wrote Makefile" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
+    grep "OK" $TMP >/dev/null && exit 1
+    exit 0
+}
+
+case $1 in
+usage) echo "./Dotest (dot|sim|ctask|systemc.code|systemc.run|vhdl) subdir [comp] [show]";;
+makefile) make_makefile $2;;
+all) make_all $2;;
+*) case $3 in
+        comp) make_target_comp $1 $2 $4;;
+        *) make_target $1 $2;;
+    esac
+esac
