Added --compiler option to do_test and do_tests scripts

diff --git a/examples/do_test b/examples/do_test
--- a/examples/do_test
+++ b/examples/do_test
@@ -1,30 +1,30 @@
 #!/bin/bash
 
+# A script for automated testing 
 
 RFSMMAKE=/Users/jserot/Dev/ml/rfsm/etc/bin/rfsmmake
 RFSMLIB=/Users/jserot/Dev/ml/rfsm/etc
 RFSMBIN=/Users/jserot/Dev/ml/rfsm/_build/default/src/bin
 IFS="/" read -ra PARTS <<< "$2"
 GUEST="${PARTS[0]}"
-RFSMC=$RFSMBIN/$GUEST/rfsmc.bc # Current version
-RFSMC_PRE=/Applications/RfsmLight.app/Contents/MacOS/rfsmc # Previous version
-
-# A script for automated testing 
+RFSMC=$RFSMBIN/$GUEST/rfsmc.bc # Default version
+# SHOW=no
 
 try_make ()
 {
 case $1 in
-dot) make dot.run;;
-sim) make sim;;
+dot.run) make dot.run;;
+dot) make dot;;
 sim.run) make sim.run;;
+sim) make sim;;
 ctask) make ctask;;
-systemc) make systemc;;
 systemc.code) make systemc.code;;
 systemc.run) make systemc.run;;
+systemc) make systemc;;
 systemc.sim) make systemc.sim;;
-vhdl) make vhdl;;
 vhdl.code) make vhdl.code;;
 vhdl.run) make vhdl.run;;
+vhdl) make vhdl;;
 vhdl.sim) make vhdl.sim;;
 *) false;;
 esac
@@ -44,17 +44,17 @@ case $? in
 esac
 }
 
-function check_results
-{
-echo -n "  -> checking $1 results ... "
-(cd $1; make $2.check) > /dev/null 2>&1
-case $? in
-0)
-  echo -e "\033[32mOK\033[0m";;
-*)
- failed=true; echo -e "\033[31m** Checking of $2 results FAILED in $1\033[0m";;
-esac
-}
+# function check_results
+# {
+# echo -n "  -> checking $1 results ... "
+# (cd $1; make $2.check) > /dev/null 2>&1
+# case $? in
+# 0)
+#   echo -e "\033[32mOK\033[0m";;
+# *)
+#  failed=true; echo -e "\033[31m** Checking of $2 results FAILED in $1\033[0m";;
+# esac
+# }
 
 function make_test 
 {
@@ -91,35 +91,35 @@ make_target ()
     exit 0
 }
 
-make_target_comp () # For regression testing
-{
-    echo -n "Making $1 in $2 (with $RFSMC_PRE)..."
-    (cd $2; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC_PRE -o Makefile ./main.pro > $TMP 2>&1)
-    case $1 in
-        systemc) (cd $2; try_make $1.code) >> $TMP 2>&1;;
-        vhdl) (cd $2; try_make $1.code) >> $TMP 2>&1;;
-        *) (cd $2; try_make $1) >> $TMP 2>&1
-    esac
-    grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
-    grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
-    (cd $2; if [ -e ./$1 ]; then rm -rf ./$1.pre; cp -r ./$1 ./$1.pre; fi)
-    (cd $2; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC -o Makefile ./main.pro >> $TMP 2>&1)
-    echo -n "Making $1 in $2 (with $RFSMC)..."
-    case $1 in
-        systemc) (cd $2; try_make $1.code) >> $TMP 2>&1;;
-        vhdl) (cd $2; try_make $1.code) >> $TMP 2>&1;;
-        *) (cd $2; try_make $1) >> $TMP 2>&1
-    esac
-    grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
-    grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
-    echo "Comparing results..."
-    case $3 in
-#        show) diff -B --unified=0 -r --exclude=Makefile $2/$1.pre $2/$1;;
-        show) diff -d -B -r --exclude=Makefile $2/$1.pre $2/$1;;
-        *) diff -q -d -B --unified=1 -r --exclude=Makefile $2/$1.pre $2/$1;;
-    esac
-#    rm -rf $2/$1.pre
-}
+# make_target_comp () # For regression testing
+# {
+#     echo -n "Making $1 in $2 (with $RFSMC_PRE)..."
+#     (cd $2; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC_PRE -o Makefile ./main.pro > $TMP 2>&1)
+#     case $1 in
+#         systemc) (cd $2; try_make $1.code) >> $TMP 2>&1;;
+#         vhdl) (cd $2; try_make $1.code) >> $TMP 2>&1;;
+#         *) (cd $2; try_make $1) >> $TMP 2>&1
+#     esac
+#     grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
+#     grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
+#     (cd $2; if [ -e ./$1 ]; then rm -rf ./$1.pre; cp -r ./$1 ./$1.pre; fi)
+#     (cd $2; $RFSMMAKE -lib $RFSMLIB -with-test-targets -no-confirm -compiler $RFSMC -o Makefile ./main.pro >> $TMP 2>&1)
+#     echo -n "Making $1 in $2 (with $RFSMC)..."
+#     case $1 in
+#         systemc) (cd $2; try_make $1.code) >> $TMP 2>&1;;
+#         vhdl) (cd $2; try_make $1.code) >> $TMP 2>&1;;
+#         *) (cd $2; try_make $1) >> $TMP 2>&1
+#     esac
+#     grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
+#     grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
+#     echo "Comparing results..."
+#     case $3 in
+# #        show) diff -B --unified=0 -r --exclude=Makefile $2/$1.pre $2/$1;;
+#         show) diff -d -B -r --exclude=Makefile $2/$1.pre $2/$1;;
+#         *) diff -q -d -B --unified=1 -r --exclude=Makefile $2/$1.pre $2/$1;;
+#     esac
+# #    rm -rf $2/$1.pre
+# }
 
 make_makefile ()
 {
@@ -130,12 +130,35 @@ make_makefile ()
     exit 0
 }
 
+while : ; do
+  case "$1" in
+    "") break;;
+    --compiler)
+        RFSMC=$2; shift;;
+    -help|--help)
+        cat <<EOF
+Usage: do_test [options] kind subdir
+where
+options: [defaults in brackets after descriptions]
+  --compiler path         path to the rfsmc compiler [default: $RFSMC]
+  # --show                  launch DOT or VCD viewer after running the test [default: no]
+  --help                  print this message
+kind=makefile|dot.run|dot|sim|ctask|systemc.code|systemc.run|systemc|systemc.sim|vhdl.code|vhdl.run|vhdl|vhdl.sim
+subdir=core|full|...
+EOF
+	exit 0;;
+    *) break;;
+  esac
+  shift
+done
+
+#echo "C=$RFSMC 1=$1 2=$2"
 case $1 in
-usage) echo "./do_test (makefile|dot|sim|sim.run|ctask|systemc|systemc.code|systemc.run|systemc.sim|vhdl|vhdl.code|vhdl.run|vhdl.sim) subdir [comp] [show]";;
 makefile) make_makefile $2;;
-all) make_all $2;;
-*) case $3 in
-        comp) make_target_comp $1 $2 $4;;
-        *) make_target $1 $2;;
-    esac
+*) make_target $1 $2;;
+#all) make_all $2;;
+# *) case $2 in
+#         comp) make_target_comp $1 $2;;
+#         *) make_target $1 $2;;
+#     esac
 esac
