Modified do_test{s} scripts to accept argument

diff --git a/examples/do_test b/examples/do_test
--- a/examples/do_test
+++ b/examples/do_test
@@ -1,9 +1,9 @@
 #!/bin/bash
 # A script for automated testing 
 
-function try_make
+try_make () 
 {
-make test
+make $1
 case $? in
 0) echo "OK";;
 *) echo "FAILED";;
@@ -12,10 +12,14 @@ esac
 
 TMP=/tmp/do_test.out
 
-echo -n "Testing in $1... "
-(cd $1; if [ -e Makefile ]; then make clean > $TMP 2>&1; fi)
-(cd $1; try_make $1 && make clean) > $TMP 2>&1
-grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
-grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
-grep "OK" $TMP >/dev/null && exit 1
-exit 0
+if [ "$#" -eq 2 ]; then
+    echo -n "Making $1 in $2... "
+    (cd $2; if [ -e Makefile ]; then make clean > $TMP 2>&1; fi)
+    (cd $2; try_make $1 && make clean) > $TMP 2>&1
+    grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
+    grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
+    grep "OK" $TMP >/dev/null && exit 1
+    exit 0
+else
+    echo "usage: $0 (dot|sim|systemc|vhdl|all) dir"
+fi
